"""add file hash

Revision ID: f80e97eba161
Revises: 
Create Date: 2026-09-04 14:12:24.226539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f80e97eba161'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunks', sa.Column('file_hash', sa.String(length=64), nullable=True))
    op.execute("UPDATE document_chunks SET file_hash = 'legacy'")
    op.alter_column('document_chunks', 'file_hash', existing_type=sa.String(length=64), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_chunks', 'file_hash')
    # ### end Alembic commands ###
